  export const REGISTER ="REGISTER";
  export const REGISTER_SUCCESS  = "REGISTER_SUCCESS";
  export const REGISTER_REFUSE  = "REGISTER_REFUSE";
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const PROFIL ="PROFIL";
export const GET_PROFIL_SUCCESS ="GET_PROFIL_SUCCESS";
export const GET_PROFIL_FAIL ="GET_PROFIL_FAIL";
